language: node_js
node_js:
   - "4.2"

branches:
  only:
    - master
    - dev
script:
  make riot
#foo
sudo: false

after_success:
  make test-sauce && make test-coveralls

notifications:
    email: false

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
