language: node_js
node_js:
  - 6

branches:
  only:
    - master
    - dev
    - next

script:
  make riot
#foo
sudo: false

after_success:
  test $TRAVIS_PULL_REQUEST == "false" && make test-sauce && make test-coveralls

cache:
  directories:
    - node_modules

notifications:
    email: false
